spring:
  jackson:
    deserialization:
      fail-on-unknown-properties: true

  datasource:
    username: root
    password: 1234
    url: jdbc:mysql://localhost:3306/real_rest_api?characterEncoding=UTF-8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        jdbc:
          lob:
            non-contextual-creation: true


logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              basicBinder: TRACE
      springframework:
        security: DEBUG
myApp:
  adminUsername: admin@gmail.com
  adminPassword: 1234
  userUsername: user@gmail.com
  userPassword: 1234
  clientId: myApp
  clientSecret: pass

